# Generated by Django 3.0.1 on 2020-02-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_question_opt4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='opt4',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
