# Generated by Django 2.2 on 2020-01-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200130_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
