# Generated by Django 2.2 on 2020-02-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_semester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
