# Generated by Django 3.0.1 on 2020-02-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200209_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='/media/users/user.png', upload_to='users'),
        ),
    ]
