# Generated by Django 2.2 on 2020-01-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='credit',
            field=models.FloatField(),
        ),
    ]
