# Generated by Django 2.2 on 2020-02-09 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20200130_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='topic',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
