# Generated by Django 3.0.1 on 2020-03-03 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_teacher_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('desp', models.CharField(blank=True, max_length=100)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('desp', models.CharField(blank=True, max_length=100)),
                ('qid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faq.Query')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Teacher')),
            ],
        ),
    ]
